import {useEffect, useState} from 'react';
import {api, type Account} from '../api/client';
import HITLModal from '../components/HITLModal';
import ViewOrchestration from '../components/ViewOrchestration';

export default function AccountDrawer({account, onClose}: {account: Account; onClose: () => void}) {
  const [timeline, setTimeline] = useState<{id: number; event_type: string; timestamp: string; summary: string; source: string}[]>([]); const [exception, setException] = useState<{id: string; airflow_dag_run_id?: string | null; hitl_task_id?: string | null} | null>(null); const [refresh, setRefresh] = useState(0);
  useEffect(() => {api.timeline(account.campaign_id, account.account_id).then(setTimeline).catch(() => setTimeline([])); api.exceptions().then(value => setException(value.items.find(item => item.account_id === account.account_id && item.hitl_task_id) || null)).catch(() => setException(null))}, [account,refresh]);
  const peak = Math.max(...account.daily_v1, ...account.daily_v2, 1);
  return <><aside className="csc-drawer"><button className="csc-close" onClick={onClose}>×</button><div className="csc-eyebrow">Account migration</div><h2>{account.account_name}</h2><div className="csc-subtitle">{account.tier} · {account.region} · {account.owner}</div><p><strong>${account.arr.toLocaleString()}</strong> ARR</p><div className="csc-toolbar"><span className={`csc-pill csc-${account.status}`}>{account.status}</span><ViewOrchestration task={account.latest_airflow_task_instance} /></div><div className="csc-card"><div className="csc-label">Telemetry trend · v1 and v2</div><div className="csc-trend">{account.daily_v1.map((value,index) => <i key={`v1-${index}`} style={{height:`${Math.max(3, value / peak * 80)}px`}} />)}{account.daily_v2.map((value,index) => <i key={`v2-${index}`} style={{height:`${Math.max(3, value / peak * 80)}px`,background:'#5bc59a'}} />)}</div><div className="csc-subtitle">Trailing seven days · legacy {account.legacy_usage.toLocaleString()} · replacement {account.replacement_usage.toLocaleString()}</div></div>{account.blocker_type && <div className="csc-note">Blocker: {account.blocker_type}. Contract evidence: {String(account.evidence?.commitment_expiry || 'none')}.</div>}{account.brief && <div className="csc-card"><div className="csc-label">Migration brief {account.brief_source === 'llm' && <span className="csc-pill csc-MIGRATED">AI generated</span>}</div><p>{String(account.brief.summary || '')}</p><strong>Next step:</strong> {String(account.brief.proposed_next_step || '')}</div>}<h3>Timeline</h3><div className="csc-timeline">{timeline.map(event => <div className="csc-event" key={event.id}><time>{new Date(event.timestamp).toLocaleString()}</time><div>{event.summary}</div><small>{event.source}</small></div>)}</div>{exception && <button className="csc-action" data-primary="true" onClick={() => setRefresh(value => value + 1)}>Decision control is available in the exception queue</button>}</aside>{exception && refresh > 0 && <HITLModal exceptionId={exception.id} task={exception.airflow_dag_run_id && exception.hitl_task_id ? {dag_id:'exception_resolution', run_id:exception.airflow_dag_run_id, task_id:exception.hitl_task_id, map_index:-1} : null} onClose={() => setRefresh(0)} onDone={() => setRefresh(0)} />}</>;
}
