import {useEffect, useState} from 'react';
import {api, type Account} from '../api/client';

export type Chip = 'straightforward'|'actively_migrating'|'no_progress'|'strategic'|'contractual'|'technical_blocker';
const chips: {id: Chip; label: string}[] = [{id:'straightforward',label:'Straightforward'},{id:'actively_migrating',label:'Actively migrating'},{id:'no_progress',label:'No progress'},{id:'strategic',label:'Strategic'},{id:'contractual',label:'Contractual'},{id:'technical_blocker',label:'Technical blocker'}];
export default function AccountTable({campaignId, statusFilter, onSelect}: {campaignId: string; statusFilter?: string; onSelect: (account: Account) => void}) {
  const [items, setItems] = useState<Account[]>([]); const [chip, setChip] = useState<Chip | ''>(''); const [q, setQ] = useState(''); const [scrollTop, setScrollTop] = useState(0);
  useEffect(() => {setScrollTop(0); api.accounts(campaignId, {...(statusFilter ? {status: statusFilter} : {}), ...(chip ? {chip} : {}), ...(q ? {q} : {})}).then(value => setItems(value.items)).catch(() => setItems([]))}, [campaignId,statusFilter,chip,q]);
  // Keep only a viewport-sized slice of the large population in the DOM.
  // The spacer rows preserve the native scrollbar and make the table feel like
  // a normal table while avoiding a browser layout pass for every account.
  const rowHeight = 70; const viewportRows = 10; const first = Math.max(0, Math.floor(scrollTop / rowHeight) - 2); const last = Math.min(items.length, first + viewportRows + 4); const visible = items.slice(first, last);
  return <div className="csc-panel"><div className="csc-toolbar">{chips.map(value => <button className="csc-chip" data-active={chip === value.id} onClick={() => setChip(chip === value.id ? '' : value.id)} key={value.id}>{value.label}</button>)}<input aria-label="Search accounts" placeholder="Search" value={q} onChange={event => setQ(event.target.value)} /></div><div className="csc-table-scroll" onScroll={event => setScrollTop(event.currentTarget.scrollTop)}><table className="csc-table"><thead><tr><th>Account</th><th>ARR</th><th>Risk</th><th>v1 usage</th><th>v2 adoption</th><th>Owner</th><th>Status</th><th>Blocker</th></tr></thead><tbody>{first > 0 && <tr aria-hidden="true"><td colSpan={8} style={{height:first * rowHeight, padding:0}} /></tr>}{visible.map(account => <tr className="csc-row" style={{height:rowHeight}} onClick={() => onSelect(account)} key={account.account_id}><td><strong>{account.account_name}</strong><br/><small>{account.account_id}</small></td><td>${account.arr.toLocaleString()}</td><td>{account.risk}</td><td>{account.legacy_usage.toLocaleString()}</td><td>{account.replacement_usage.toLocaleString()}</td><td>{account.owner}</td><td><span className={`csc-pill csc-${account.status}`}>{account.status.replaceAll('_',' ')}</span></td><td>{account.blocker_type || '—'}</td></tr>)}{last < items.length && <tr aria-hidden="true"><td colSpan={8} style={{height:(items.length - last) * rowHeight, padding:0}} /></tr>}</tbody></table></div>{!items.length && <div className="csc-empty">No accounts match the current filters.</div>}</div>;
}
